package pl.licznikgps
import android.Manifest
import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.location.*;import android.os.IBinder;import androidx.core.app.NotificationCompat;import java.text.SimpleDateFormat;import java.util.*
class GpsService:Service(){
 private lateinit var lm:LocationManager;private var last:Location?=null
 override fun onCreate(){super.onCreate();val nm=getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager;nm.createNotificationChannel(NotificationChannel("gps","Licznik GPS",NotificationManager.IMPORTANCE_LOW));startForeground(1,NotificationCompat.Builder(this,"gps").setContentTitle("Licznik GPS").setContentText("GPS aktywny — trasa jest liczona").setSmallIcon(android.R.drawable.ic_menu_mylocation).setOngoing(true).build());getSharedPreferences("gps",0).edit().putBoolean("running",true).apply();lm=getSystemService(Context.LOCATION_SERVICE) as LocationManager;if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){stopSelf();return};lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,1000L,3f,listener)}
 private val listener=LocationListener{loc->val p=last;if(p!=null&&loc.accuracy<=50f){val d=p.distanceTo(loc)/1000.0;if(d>0&&d<=0.3){val s=getSharedPreferences("gps",0);s.edit().putFloat("km",s.getFloat("km",0f)+d.toFloat()).putFloat("speed",loc.speed*3.6f).apply();sendBroadcast(Intent("pl.licznikgps.UPDATE").setPackage(packageName))}};last=loc}
 override fun onDestroy(){if(::lm.isInitialized)try{lm.removeUpdates(listener)}catch(_:Exception){};val s=getSharedPreferences("gps",0);val k=s.getFloat("km",0f);if(k>0.01f){val set=s.getStringSet("history",HashSet())!!.toMutableSet();val now=SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.getDefault()).format(Date());set.add(now+" — "+String.format(Locale.US,"%.2f",k)+" km");s.edit().putStringSet("history",set).putBoolean("running",false).apply()}else s.edit().putBoolean("running",false).apply();sendBroadcast(Intent("pl.licznikgps.UPDATE").setPackage(packageName));super.onDestroy()}
 override fun onBind(i:Intent?):IBinder?=null
}